### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by lepardov2020** [nstrayer/datadrivencv#9]
Greetings Nick,
nice package! although I haven´t been able to install it from your git_hub.  I fixed a few things like the Rtools (hopefully) but still receiving this error message (below). Basically package ‘icon’ is not available (for R version 3.5.3), do I need to install an older version or R? it does not sound like a good way to go for other things. Could you please provide feedback?

Thanks !
L

Skipping 1 packages not available: icon
Installing 55 packages: dplyr, tidyr, glue, googlesheets4, lubridate, purrr, usethis, pagedown, fs, icon, ellipsis, pkgconfig, R6, Rcpp, rlang, tibble, tidyselect, BH, stringi, vctrs, lifecycle, hms, curl, gargle, googledrive, ids, rematch2, cli, gh, git2r, rstudioapi, whisker, withr, yaml, rmarkdown, bookdown, htmltools, jsonlite, processx, servr, httpuv, xfun, websocket, fansi, pillar, digest, mime, sys, uuid, backports, knitr, tinytex, ps, promises, AsioHeaders
Installing packages into ‘C:/Users/admin/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)

Error: Failed to install 'datadrivencv' from GitHub:
  (converted from warning) package ‘icon’ is not available (for R version 3.5.3)

**Comment by jgammerman** [comment]
I have the same issue with R version 3.6.2

**Comment by nstrayer** [comment]
Interesting. I did recently fix a missing icon dependency (https://github.com/nstrayer/datadrivencv/issues/5). I am working with R 3.6.3 so you definitely should not need to downgrade R. I would say upgrade R but given that @jgammerman is having the same issue with a 3.6.2 i'm curious.

**Comment by nstrayer** [comment]
@jgammerman would you mind pasting your full error message when running `devtools::install_github('nstrayer/datadrivencv')`?

**Comment by jgammerman** [comment]
Hi Nick, sure:

```
ERROR: dependency ‘icon’ is not available for package ‘datadrivencv’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/datadrivencv’
Error: Failed to install 'datadrivencv' from GitHub:
  (converted from warning) installation of package ‘/var/folders/50/15xvjy494fxdxr2yw09lp8gm0000gr/T//RtmpgTwME3/fileaa355c3ea598/datadrivencv_0.1.0.tar.gz’ had non-zero exit status
```

This comes after being told by RStudio that I should upgrade the Rcpp package from version 1.04 :

```
Downloading GitHub repo nstrayer/datadrivencv@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                           
2: CRAN packages only            
3: None                          
4: Rcpp (1.0.4 -> 1.0.4.6) [CRAN]
```

When I try to upgrade Rcpp to 1.04.6 from a non-compiled source I get an error:

```
ERROR: compilation failed for package ‘Rcpp’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp’
Error: Failed to install 'datadrivencv' from GitHub:
  (converted from warning) installation of package ‘Rcpp’ had non-zero exit status
```

**Comment by lepardov2020** [comment]
update: Just upgraded my R to 3.6.1 in case, but the issue continues.Thanks

**Comment by nstrayer** [comment]
Given that this issue is happening a lot I think the best path is to remove the `icon` dependency entirely. Seems to be causing all sorts of problems.

**Comment by spkaluzny** [comment]
The `icon` package was never on CRAN, it is available as a Github package. On 2020-05-20, a package named `ICON` was added to CRAN:
   ` ICON: Provides Easy Access to Complex Systems Datasets`
I believe that CRAN does not allow package names to differ only in case.

**Comment by nstrayer** [comment]
In #11, I now properly import the icon dependency using a remote import instead of the default depends the uses CRAN packages. My local testing from fresh install worked but I will wait to close until others have success.

**Comment by lepardov2020** [comment]
Nick it has worked for me, at least with your CV as an example, will see how I do with mine! thanks a lot, congrats!

**Comment by davidmihalyi** [comment]
I had to install icon manually from github, but it worked fine after that!

**Comment by jgammerman** [comment]
Hi Nick, it's also worked for me after installing icon from github with `devtools::install_github('ropenscilabs/icon')`

Thanks!

**Comment by ries9112** [comment]
Ran into this issue today and was not able to resolve with the install of `icon`.

After running `devtools::install_github('ropenscilabs/icon')` I still see the same error that was outlined in this issue:
<img width="832" alt="image" src="https://user-images.githubusercontent.com/32306488/110060586-5ea2ff80-7d23-11eb-9f6d-b735dfbb207b.png">


I tried doing the downloads for the icons (i.e. `download_academicons()`) until GitHub blocked me from any further downloads so if a specific download is needed here it would be good to outline that in this issue:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/32306488/110060501-40d59a80-7d23-11eb-934f-6f91cf481bed.png">

**Comment by derek-chan** [comment]
The package has been renamed to icons
https://github.com/mitchelloharawild/icons

First run `devtools::install_github('mitchelloharawild/icons')`. In the `DESCRIPTION` file of `datadrivencv` package you will need to update `icon` to `icons`..

**Comment by bmill3r** [comment]
Ran into this problem while trying to install `devtools::install_github("nstrayer/datadrivencv")` but after trying several solutions posted above it worked for me. Posting here in case anyone else needs some suggestions or runs into the same issues.

Initial error:
```
ERROR: dependency ‘icon’ is not available for package ‘datadrivencv’
* removing ‘/Users/Library/R/4.0/library/datadrivencv’
Warning messages:
1: package ‘icon’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
2: Perhaps you meant ‘ICON’ ? 
3: In i.p(...) :
  installation of package ‘/var/folders/cf/llylf0sn67j0qlvgy3_990ym0000gn/T//RtmpaCgTYE/file159c03347a307/datadrivencv_0.1.0.tar.gz’ had non-zero exit status
```

So naturally tried doing:

```
> install.packages("ICON")
```

But as stated above this is not the correct dependency.

So then tried:

```
> devtools::install_github('ropenscilabs/icon')
```

which installed:

```
Downloading GitHub repo ropenscilabs/icon@HEAD
✓  checking for file ‘/private/var/folders/cf/llylf0sn67j0qlvgy3_990ym0000gn/T/RtmpaCgTYE/remotes159c01f496ad4/mitchelloharawild-icons-dc35a3b/DESCRIPTION’ ...
─  preparing ‘icons’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘icons_0.2.0.tar.gz’
   
* installing *source* package ‘icons’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
! No icons are currently available, start by downloading icons with the download_*() functions.
** testing if installed package can be loaded from final location
! No icons are currently available, start by downloading icons with the download_*() functions.
** testing if installed package keeps a record of temporary installation path
* DONE (icons)
```

As you can see, this installed `icons` but not the dependency `icon`.
So I still got same error when trying `devtools::install_github("nstrayer/datadrivencv")`

So then finally came to the solution posted above (#57):

```
> remotes::install_github('mitchelloharawild/icons@v0.1.0')
```

This worked for me.

```
Downloading GitHub repo mitchelloharawild/icons@v0.1.0
✓  checking for file ‘/private/var/folders/cf/llylf0sn67j0qlvgy3_990ym0000gn/T/RtmpaCgTYE/remotes159c019ff6ea1/mitchelloharawild-icons-4ef7ed0/DESCRIPTION’ ...
─  preparing ‘icon’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘icon_0.1.0.tar.gz’
   
Installing package into ‘/Users/Library/R/4.0/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘icon’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (icon)
```

```
> devtools::install_github("nstrayer/datadrivencv")
Downloading GitHub repo nstrayer/datadrivencv@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                         
2: CRAN packages only                          
3: None                                        
4: icon (4ef7ed0a8... -> dc35a3b79...) [GitHub]
```

I actually skipped updating just in case there might be an issue with the versions. But after all that `datadrivencv` installed successfully.
